stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE
  VENV_DIR: "venv"

before_script:
  - apt-get update -qq && apt-get install -qq -y python3 python3-pip python3-venv
  - python3 -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate
  - pip install --upgrade pip
  - pip install dvc[all]
  - pip install -r requirements.txt
  - pip install pytest  # Устанавливаем pytest

cache:
  paths:
    - .dvc/cache
    - $VENV_DIR

test:
  stage: test
  script:
    - source $VENV_DIR/bin/activate
    - dvc pull -v
    - python data_executor.py
    - pytest test_*.py
    
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHA .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main
  tags:
    - docker

deploy:
  stage: deploy
  script:
    - echo "Deploying to production server"
    - docker run -d -p 8501:8501 $DOCKER_IMAGE:$CI_COMMIT_SHA
  only:
    - main
